export const plans = [
  {
    name: "EXPOSURE DISPLAY",
    monthly: 15.5,
    annual: 15.5 * 12 * 0.75,
    ticks: 1,
    color: "from-blue-900 to-blue-600",
    features: [
      "Communication Browser Access",
      "Social Media Optimization",
      "1% Application Demand Fee",
      "Design-Kit System Admission",
      "Consultation Membership Meetings",
      "Website Dashboard Attendance",
      "Online Shopping Authorization",
      "Application Media Features",
      "Development Marketing Protocols",
      "Application Customer Support",
      "Acknowledged Associated Partner",
    ],
  },
  {
    name: "COPPER COMMUNITY",
    monthly: 28.5,
    annual: 28.5 * 12 * 0.75,
    ticks: 3,
    color: "from-orange-900 to-orange-600",
    features: [
      "Communication Browser Access",
      "Social Media Optimization",
      "1% Application Demand Fee",
      "Design-Kit System Admission",
      "Consultation Membership Meetings",
      "Website Dashboard Attendance",
      "Online Shopping Authorization",
      "Application Media Features",
      "Development Marketing Protocols",
      "Application Customer Support",
      "Acknowledged Associated Partner",
    ],
  },
  {
    name: "SILVER SOCIAL DESIGN",
    monthly: 62.5,
    annual: 62.5 * 12 * 0.75,
    ticks: 7,
    color: "from-gray-800 to-gray-500",
    features: [
      "Communication Browser Access",
      "Social Media Optimization",
      "1% Application Demand Fee",
      "Design-Kit System Admission",
      "Consultation Membership Meetings",
      "Website Dashboard Attendance",
      "Online Shopping Authorization",
      "Application Media Features",
      "Development Marketing Protocols",
      "Application Customer Support",
      "Acknowledged Associated Partner",
    ],
  },
  {
    name: "GOLDEN ASSOCIATION",
    monthly: 96.5,
    annual: 96.5 * 12 * 0.75,
    ticks: 999,
    color: "from-yellow-700 to-yellow-500",
    features: [
      "Communication Browser Access",
      "Social Media Optimization",
      "1% Application Demand Fee",
      "Design-Kit System Admission",
      "Consultation Membership Meetings",
      "Website Dashboard Attendance",
      "Online Shopping Authorization",
      "Application Media Features",
      "Development Marketing Protocols",
      "Application Customer Support",
      "Acknowledged Associated Partner",
    ],
  },
];